services:
  gestionCoupon:
    build: ./Coupon
    image: arbiferchichi/coupon
    container_name: coupon-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./livraison/.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql


  livraison:
    image: arbiferchichi/livraison
    container_name: livraison-service

    depends_on:
      - mysqldb
      - eureka-server
      
    build: ./livraison
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/livraison?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'


    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true



  reclamation:
    image: anisfarjallah/reclamation
    container_name: reclamation
  
    depends_on:
      - mysqldb
      - eureka-server
        
    build: ./BackSpring-MicroS
    restart: on-failure
    ports:
      - 8075:8075
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/recbase?createDatabaseIfNotExist=true&useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "root",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
  
  
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  eureka-server:
    build: ./eurukaServer
    image: arbiferchichi/eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  api-gateway:
    build: ./api-Gatway
    image: arbiferchichi/apigateway
    container_name: apigateway
    ports:
      - "8009:8009"
    environment:
     

      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - livraison
      - keycloak

volumes:
  db: